services:
  - type: web
    name: somablanks
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: false
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
